### ISSUE TITLE
boundary service api

### ISSUE THREAD

**Issue by sethvincent** [openseattle/seattle-boundaries#13]
it sure would be cool to have an api server that acts as a boundary service.

this could be reused, but it is a django/postgis project and from what i remember needs shapefiles: https://github.com/newsapps/django-boundaryservice

i'd prefer to make a simple api with node.js & maybe elasticsearch.

**Comment by sethvincent** [comment]
:zap: http://github.com/seattleio/boundaries.seattle.io
:zap: http://boundaries.seattle.io

**Comment by stedy** [comment]
:zap: is indeed the right thing to say about these, super cool!
