### ISSUE TITLE
add police beats/precincts

### ISSUE THREAD

**Issue by sethvincent** [openseattle/seattle-boundaries#5]
Sources:
- beats: https://data.seattle.gov/Public-Safety/Spd-Beats-2015/yutr-ryap
- precincts: https://data.seattle.gov/Public-Safety/Spd-Precincts/3rtr-jjhz
- micro community policing plan areas: https://github.com/openseattle/seattle-boundaries/tree/master/source/mcpp-areas

**Comment by stedy** [comment]
I did these mostly by hand which means there are likely some errors but this is my best attempt from what I could see/guess from the SPD pdf files.

**Comment by sethvincent** [comment]
Reopening this one with the discovery of these sources:
- beats: https://data.seattle.gov/Public-Safety/Spd-Beats-2015/yutr-ryap
- precincts: https://data.seattle.gov/Public-Safety/Spd-Precincts/3rtr-jjhz

I'm also about to check in some shape files for SPD's micro community policing plan areas.

**Comment by sethvincent** [comment]
Updated the original issue with relevant links. I may be able to work on this tomorrow evening.

**Comment by sethvincent** [comment]
added spd beats, precincts, and mcpp areas.

we need a place to document how to generate the mcpp areas and other datasets.

i used gdal and [sph2json](http://npmjs.com/shp2json)

```
shp2json source/mcpp-areas.zip > data/spd-mcpp-areas.geojson
```

**Comment by stedy** [comment]
Those new shapefiles look so nice! :gem:
